version: "3"


services:
  redis:
    image: redis
    container_name: 'redis'
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
  mailcheck_service:
    build: .
    container_name: mailcheck_service
    command: uvicorn main.asgi:app --proxy-headers --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    image: app-image
