name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: mailcheck_service-image

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg github_private_key='${{ secrets.SSH_SERVER_KEY }}' . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo '${{ secrets.YC_REGISTRY_KEY }}' | docker login --username json_key --password-stdin cr.yandex

      - name: Push image
        run: |
          VERSION="latest"
          IMAGE_ID=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          script: |
            docker-compose stop mailcheck_service
            docker-compose pull mailcheck_service
            docker-compose up -d mailcheck_service
